name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: reporter
        run: |
          curl 'https://raw.githubusercontent.com/GarnerCorp/build-actions/5850ddad13d8a78661af64b1b9de473c33290b8b/yarn/reporter.json' > reporter.json
          echo "::add-matcher::$(pwd)/reporter.json"

      - name: Run a multi-line script
        run: |
          echo <<'EOF'
              ➤ YN0060: │ @angular/cdk is listed by your project with version 19.2.18 (pfce34), which doesn't satisfy what @angular/material requests (19.2.17).
              ➤ YN0060: │ dompurify is listed by your project with version 3.2.6 (peb1b9), which doesn't satisfy what something.js requests (3.2.4).
              ➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
              ➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
            ➤ YN0000: └ Completed
          EOF
